// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAGIOY54bKtZ6Jo04aDCMLk9iSD3mCAPw',
    appId: '1:737500894319:web:13a47bf276e8e89749699a',
    messagingSenderId: '737500894319',
    projectId: 'greenroot-99bf8',
    authDomain: 'greenroot-99bf8.firebaseapp.com',
    storageBucket: 'greenroot-99bf8.appspot.com',
    measurementId: 'G-YRL3J70669',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYvwVSHALEORTLsYHNQ36CvOo8mCuy680',
    appId: '1:737500894319:android:f7bdf3e67545042449699a',
    messagingSenderId: '737500894319',
    projectId: 'greenroot-99bf8',
    storageBucket: 'greenroot-99bf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfFWuFc8x5yKB9ZxTW8_D3MOTnv9M7cgg',
    appId: '1:737500894319:ios:5be058fcf21a29aa49699a',
    messagingSenderId: '737500894319',
    projectId: 'greenroot-99bf8',
    storageBucket: 'greenroot-99bf8.appspot.com',
    iosBundleId: 'com.example.elearner',
  );
}
